[tool.poetry]
name = "kfs"
version = "0.1.0"
description = "Kramer's File System"
authors = ["Matt Kramer <matthew.robert.kramer@gmail.com>"]
packages = [
    { include = "kfs", from = "src" },
]

[tool.poetry.scripts]
kfs = 'kfs.cli:app'

[tool.poetry.dependencies]
python = "^3.9"

rich = "^11.0.0"
sqlmodel = "^0.0.6"
typer = "^0.4.0"

# Optional dependencies
codecov = {version = "^2.1.12", optional = true}

[tool.poetry.dev-dependencies]
black = "^21.12b0"
mypy = "^0.931"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
toml = "^0.10.2"

[tool.poetry.extras]
ci = ["codecov"]

[tool.isort]
profile = "black"
#multi_line_output = 3  # Allow multiple imports on a line, but split when too long
force_single_line = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
