[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "setuptools-scm[toml]>=6.2"]

[project]
authors = [
  {name = "Matt Kramer", email = "matthew.robert.kramer@gmail.com"}
]
dependencies = [
  "rich<=13.3.5",
  "sqlmodel<=0.0.8",
  "typer<=0.7.0"
]
description = "Kramer's File System"
dynamic = ["version"]
license = {text = "MIT"}
name = "kfs"
requires-python = ">=3.10"

[project.optional-dependencies]
ci = ["tox"]
dev = [
  "mypy<=0.991",
  "pytest<=6.2.5",
  "pytest-cov<=4.0.0",
  "toml<=0.10.2",
  "tox"
]

[project.scripts]
kfs = "kfs.cli:app"

[tool.distutils.bdist_wheel]
universal = true

[tool.isort]
force_single_line = true
profile = "black"

[tool.setuptools_scm]
version_scheme = "post-release"
