name: Run Python Tests

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    tags: v[0-9]+.[0-9]+.[0-9]+*

jobs:
  test:
    name: Run Tests, Python ${{ matrix.python-version }}
    runs-on:
      labels: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
    steps:
    - name: Check out repository
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

    - name: Set up python ${{ matrix.python-version }}
      uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0 # v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install CI packages
      run: pip install ".[ci]"

    - name: Run tox
      run: tox

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        files: ./test-reports/coverage.xml
